name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --python ${{ matrix.python-version }}
      - name: Run Tests
        run: pipenv run python -m unittest discover -s src -v

  end-to-end-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --python ${{ matrix.python-version }}
      - name: Run Code
        run: pipenv run python src/determine_transformation.py data/000000.png data/000000.txt data/000001.png data/000001.txt data/calibration.txt